  
- name: "upgrade packages."
  become: true
  become_method: sudo
  apt:
   update_cache: "yes"

- name: "install dependencies."
  become: yes
  apt:
   name: ["nodejs", "npm"]
   state: present
   update_cache: yes

