
- name: "Extract artifact.tar.gz file to EC2 instance"
  unarchive:
   src: ../../backend/dist/artefacts.tar.gz
   dest: /home/ubuntu/
   owner: ubuntu
   remote_src: yes
  
- name: "upgrade packages."
  become: true
  become_method: sudo
  apt:
   update_cache: "yes"

- name: "install dependencies."
  become: yes
  apt:
   name: ["nodejs", "npm"]
   state: present
   update_cache: yes
    
- name: "Install netstat tool"
  become: yes
  apt:
   name: ["net-tools"]
   state: present
   update_cache: yes

- name: "install pm2"
  become: yes
  shell: |
    cd /home/ubuntu/
    npm install pm2 -g
    
- name: "Check if port 3030 is open"
  become: yes
  become_user: ubuntu
  shell: |
   cd /home/ubuntu/dist
   pm2 list
   pm2 stop default
   pm2 start main.js -n "udapeople-backend"
   pm2 status all
   netstat -tulpn
   curl localhost:3030/api/status
   netstat -tulpn
  ignore_errors: true  
